// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Memento",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Memento",
            targets: ["AppModule"],
            bundleIdentifier: "com.isha.Memento",
            teamIdentifier: "B94476A9R8",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .butterfly),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
 
                .landscapeRight,
                .landscapeLeft
 
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources"),
                .process("Fonts")
            ]
        )
    ]
)
